### ISSUE TITLE
M1 version

### ISSUE THREAD

**Issue by 0x3333** [Annex-Engineering/klipper_estimator#12]
Despite the fact that the x86_64 version works great on M1 Macs, is it on the horizon of providing an ARM64 version for OS X?

**Comment by dalegaard** [comment]
Hi!

GitHub currently doesn't provide M1 action runners, and cross compiling has proven difficult for OS X. I don't have any experience with it, so I doubt we'll be able to provide M1 binaries for the foreseeable future. That said, once GitHub does provide M1 action runners it should be easy enough to provide release binaries for the M1 as well. I'll be sure to keep an eye out.

Until then an option is to compile the tool yourself, I think the build steps are the same on an M1 Mac as any other OS. Feel free to file an issue if you go this route and it doesn't work :)

Best regards
Lasse
