### ISSUE TITLE
One-off error in `OperationSequence::process`?

### ISSUE THREAD

**Issue by Piezoid** [Annex-Engineering/klipper_estimator#16]
There is some things that I don't understand in klipper_estimator `OperationSequence::process`:

As I understand it, on a partial flush, the loop looks in reverse order for a move with an entry velocity that doesn't depend on the following moves. This will act as the starting point for propagating peak velocity to previous moves. When such move can't be found in the unplanned part of the buffer, nothing is done or yielded downstream. 

When this search reaches an non-move operation which is also the first unplanned operation, it sets `flush_count` to its index. This enables the operation to be readily yielded by `next_move`. At least, I think this is the intent of [this code](https://github.com/Annex-Engineering/klipper_estimator/blob/e9cfd7e12097da8d1246607bdad917a99de0fe7d/lib/src/planner.rs#L578-L582).

Now the issue is that `self.flush_count + 1` is actually the index of the second operation in the unplanned part of the buffer.

Another thing that I noticed: when the search can't find starting point for planing, `self.flush_count` is set to 0, which will plan again the moves at the start of the buffer. Not sure if this intended, but otherwise, the old value should be left alone. 
Your implementation also recompute the planning of all moves during a complete flush (`!partial`), I don't think the original implementation does this.

Maybe I'm missing something, this literal translation from optimized python was quite difficult for me to grasp...

**Comment by Piezoid** [comment]
Thanks for the detailed reply!

> Setting `flush_count` to zero when nothing could be planned is indeed intended, during partial flushes, as it means the total duration of the buffered moves wasn't long enough to ensure that no future moves could affect them.

I was noting that partial flushes that cannot plan anything shouldn't mark previously planned moves as unplanned. Although, this doesn't matter when pull driven: planned moves are all removed from the queue before the next partial flush.

> I'm not really happy with how this part turned out, as you note it's basically a direct port, warts and all. At some point when I have time I'll go through it and see if I can improve it a bit.

I came with these questions while refactoring the planner to avoid mutations and "make the monoids more explicit". My goal was understanding the pipeline better before trying some variations (like tagging values to get the originals limits). If I end up with something simple enough I'll make a PR, but I fear that this project want to keep the code layout close to Klipper's for maintenance reasons.

**Comment by dalegaard** [comment]
I just pushed a commit that properly splits move sequences. I discovered, based on your input, that my last changes, making `G4` pauses instead of indeterminate dwells, resulted in potential issues.

MoveSequences no longer contain timeouts, as those were the potential issue. Instead, there's now an `OperationSequence` which contains dwells and move sequences. This means `MoveSequence::process`(formerly `OperationSequence::process`) no longer handles non-moves at all. I did add a small optimization in the form of a loop to advance over any fill commands in a move sequence.

**Comment by Piezoid** [comment]
> MoveSequences no longer contain timeouts, as those were the potential issue. Instead, there's now an `OperationSequence` which contains dwells and move sequences. This means `MoveSequence::process`(formerly `OperationSequence::process`) no longer handles non-moves at all. I did add a small optimization in the form of a loop to advance over any fill commands in a move sequence.

Nice! I'll close this, as it solves the issue.
