### ISSUE TITLE
ParseError with macros using leading underscore

### ISSUE THREAD

**Issue by Deynix** [Annex-Engineering/klipper_estimator#27]
To help keep my macro menu uncluttered I have leading underscores on a lot of my macros including the start/end macros (_START_PRINT and _END_PRINT). When attempting to use klipper_estimator it throws an error if these macros are used:

thread 'main' panicked at 'gcode read: ParseError(GCodeParseError { position: "_START_PRINT BED_TEMP=70 EXTRUDER_TEMP=215" })', tool\src\cmd\estimate.rs:202:27

If I remove the leading underscores and just call them "START_PRINT" and "END_PRINT", the parse runs correctly.

Using a freshly-built copy of klipper_estimator 2.0.4 on Windows 10; slicer is SuperSlicer 2.5.59.0.

**Comment by dalegaard** [comment]
Hi @Deynix

This is now fixed in commit 8997799, released as v2.0.5.

Thanks for reporting!

Best regards,
Lasse
