### ISSUE TITLE
Failed to run klipper_estimator

### ISSUE THREAD

**Issue by Tomek5111** [Annex-Engineering/klipper_estimator#45]
Hello
i get an error when i want to slice the file and transfer it to klipper.

Fallen to run klipper_estimator
b'thread main panicked at \'gcode read: IO(Error {kind: InvalidData, message: "stream did not contain valid UTF-8" }\, tool/ src/cmd/post_process.rs:355:27\nnote: run with 'RUST_BACKTRACE=1 environment variable to display a backtrace\n'

I use
klipper-preprocessor and I also entered where the klipper_estimator is located

**Comment by dalegaard** [comment]
Hi @Tomek5111 

This is caused by one or more lines in the input file containing non-UTF8 characters. As gcode should always follow this, you are seeing a bug in whatever is outputting the gcode(I'm assuming Cura).

Best regards,
Lasse
