### ISSUE TITLE
FR: Rename function

### ISSUE THREAD

**Issue by Arakon** [Annex-Engineering/klipper_estimator#46]
Most slicers offer the option to put the print time as a part of the filename. Would it be possible to update that time/attach the actual print time (rounded to hours and minutes) in the filename?
i.e. I get the filename: "Testobject_ASA_1h43m.gcode", but klipper_estimator calculates an actual 2:28 print time. If the name could be changed to "Testobject_ASA_2h28m.gcode" before uploading to Klipper, that'd make it much easier to see at a glance what jobs to print next.

**Comment by dalegaard** [comment]
Hi @Arakon 

It's not possible to do this, as the tool is called with the path already given by the slicer. We have no way to affect the resulting output file name in a general way.

Best regards,
Lasse
