### ISSUE TITLE
Display Popup Window with Estimate after Slicing/Export / Possible bug in layer time output

### ISSUE THREAD

**Issue by MKloberg** [Annex-Engineering/klipper_estimator#48]
I'm currently doing speed Benchies and your simulator has been super insightful in understanding what is going on in terms of flow and estimating the total time it will take to print / where time is spent.
I'm using Orca and couldn't find a way to just pop-up a window with the estimate after slicing, look at it and make decisions based on what I'm seeing in terms of the additional data I'm getting now. 

So I made this PowerShell wrapper that does exactly that. It practically avoids a lot of wasted filament and time, streamlining the workflow to a point that is near perfect, because one can avoid all this physical testing when changing this one thing the slicer that one thinks might make it go faster. We can simulate everything now! :-)
I had a lot of problems with spaces in file system paths while doing this, it fixes all that as well.

Feel free to release this along with the project, it works great and should work in all slicers I think.

Why this is an issue?
There seems to be a bug in the output of the simulator. I also wanted to capture the output and write it next to g-code file in addition to displaying it, so I can look at it later. This works but only up until the:
!!! Layer Time Distribution !!! is printed.
For some reason, no matter what I tried in PowerShell or simple CMD, as soon as you pipe the output into a file, it hangs up the process at that very point. 
I suspect there is a stream, or a pipe not being closed properly in the layer time distribution output.
It works fine against a console, but as soon as you try to capture the output in any shape or form it hangs up on the last part being written.

Suggestions:
Either fix why this is happening or provide a switch that causes the layer time distribution to NOT print.
Some switches in general to control which sections are printing would be awesome in this use case, I personally don't care much about the layer distribution (which can be quite long and causes the pop up window to scroll up, having to scroll back to the top).

Hope this helps :-)
Mac

[Run_Klipper_Estimator.zip](https://github.com/Annex-Engineering/klipper_estimator/files/13314498/Run_Klipper_Estimator.zip)

![image](https://github.com/Annex-Engineering/klipper_estimator/assets/13971502/a48a633c-4d0d-4b3b-9e07-b2aebcf49176)

**Comment by dalegaard** [comment]
Hi @MKloberg 

I just released version 3.6.0, it has `--omit-layer-times` and `--omit-move-kinds` options to disable respectively the layer times and move kind distributions.

I believe the reason you were seeing the layer time distribution never finishing printing, is that there's some terminal-width-based formatting to print the layer times in columns for compactness. This probably doesn't work correctly in all cases. I don't want to mess too much with this stuff, I think if someone wants to use the output in their own tools they should probably be using the `json` output format instead.

Best regards,
Lasse
