### ISSUE TITLE
FR: Arc Support

### ISSUE THREAD

**Issue by samwiseg0** [Annex-Engineering/klipper_estimator#5]
When running `klipper_estimator` on an arc-welded file it provides wildly incorrect estimates. Ideally, the gcode file could be processed through `klipper_estimator` after its been arc-welded.

**Comment by dalegaard** [comment]
Hi!

Currently gcode arcs aren't supported. I'll look into how difficult it would be to support.

Best regards,
Lasse

**Comment by SnorreSelmer** [comment]
Klipper recommends _against_ using arcs... You save a bit of file-size, but gain nothing in quality over not using arcs.

https://klipper.discourse.group/t/arc-movement-g2-g3/490/3

**Comment by samwiseg0** [comment]
> Klipper recommends _against_ using arcs... You save a bit of file-size, but gain nothing in quality over not using arcs.
> 
> [klipper.discourse.group/t/arc-movement-g2-g3/490/3](https://klipper.discourse.group/t/arc-movement-g2-g3/490/3)

Not seeing where it is not recommended? Regardless, asking to support something that klipper itself supports is valid and whether or not it is recommend is not really pertinent in this issue.

**Comment by dalegaard** [comment]
Added in #2c7b578, released as v3.2.0.
