### ISSUE TITLE
Microsoft Defender says: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by freakydude** [Annex-Engineering/klipper_estimator#55]
Hi,

I don't know if it is a temporary problem ... but at the moment the Win11 Microsoft defender says the current klipper_estimator.exe (v 3.7.0) has a Trojan:Win32/Wacatac.B!ml and quarantains the file

![grafik](https://github.com/Annex-Engineering/klipper_estimator/assets/32776748/4e9dee8b-220e-4ce0-bdb2-56508302bc62)

With best regards,
freakyDude

**Comment by dalegaard** [comment]
Hi,

I guess this is a false positive from Windows Defender. I really have no way of fixing that. You can try compiling the tool yourself following the README file.

Best regards,
Lasse

**Comment by freakydude** [comment]
The windows defender stops with 3.7.1 to detect the "virus"
