### ISSUE TITLE
incorrect estimate result

### ISSUE THREAD

**Issue by vit-sh** [Annex-Engineering/klipper_estimator#60]
incorrect estimate result
version: 3.7.2 and 3.7.1
os: windows

let builder = Config::builder()
    .set_default(
        "max_accel_to_decel",
        Value::new(None, ValueKind::Float(50.0)),
    )
override minimum_cruise_ratio some times

**Comment by dalegaard** [comment]
No info, can't reproduce.

Best regards,
Lasse
