### ISSUE TITLE
override minimum_cruise_ratio some times

### ISSUE THREAD

**Issue by vit-sh** [Annex-Engineering/klipper_estimator#62]
Test configuration file with script in the test.zip archive. The script cyclically launches klipper_estimate with a dump into a configuration file with the launch number. The result is in the resilt.zip archive. The default value for the max_accel_to_decel parameter is periodically substituted (files 3,4,7,11,14,18,19).
[test.zip](https://github.com/Annex-Engineering/klipper_estimator/files/15079176/test.zip)
[result.zip](https://github.com/Annex-Engineering/klipper_estimator/files/15079175/result.zip)

PS. the same result in the linux version

**Comment by dalegaard** [comment]
Hi @vit-sh 

This should be fixed now. Can you confirm on latest release? 

Best regards, 
Lasse

**Comment by vit-sh** [comment]
I confirm. Everything works perfectly.
