### ISSUE TITLE
How to EXTRACT dump-moves informations into an external file

### ISSUE THREAD

**Issue by sb53systems** [Annex-Engineering/klipper_estimator#65]
Hi everyone, is there a way to extract all the information obtained by the dump-moves command into a text file to be able to examine the whole thing.

**Comment by dalegaard** [comment]
This is a feature of the shell called "redirection".

```
`klipper_estimator ... > filename
```

Best regards,
Lasse

**Comment by sb53systems** [comment]
thanks bro
