### ISSUE TITLE
Support for the acceleration change set by orcaslicer with Emit Limits in G-Code option

### ISSUE THREAD

**Issue by sb53systems** [Annex-Engineering/klipper_estimator#66]
How to include the acceleration change set by orcaslicer with Emit Limits in G-Code option ?
![346765550-afe5a207-44ec-4725-8164-2f49cd392856](https://github.com/Annex-Engineering/klipper_estimator/assets/33290411/13cea0ac-8df8-40b3-950a-ff1f52db0390)
![image](https://github.com/Annex-Engineering/klipper_estimator/assets/33290411/2db8e7d9-1d05-4b16-aef8-75055810db47)  
  
![image](https://github.com/user-attachments/assets/316333e1-bd60-4aa6-93da-8b68ef16ed5c)

Thank you.

**Comment by sb53systems** [comment]
this small time difference is due to this missing parameter  
  
![image](https://github.com/user-attachments/assets/a4337041-fdfe-4b5b-b317-c8a2c9a973fa)

**Comment by dalegaard** [comment]
Hi,

I'm not sure what's being reported here. 

Best regards, 
Lasse

**Comment by sb53systems** [comment]
Hey Lasse,

I think that Klipper_Estimator_Script uses the maximum printer acceleration
provided in the Config.json file to estimate the time of each movement and
its flow rate average, and does not support the acceleration defined in the
G-Code, Example :

SET_VELOCITY_LIMIT ACCEL=1400 ACCEL_TO_DECEL=700
G1 F9000
G1 X35 Y48
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
G1 F3600
G1 X40 Y50

I noticed this because the time estimated by Klipper_Estimator is always
the same whether the option  (Emit Limits to G-code) is activated or not.

My Config.json File is below

{
  "max_velocity": 300.0,
  "max_acceleration": 6000.0,
  "minimum_cruise_ratio": 0.5,
  "square_corner_velocity": 5.0,
  "instant_corner_velocity": 1.0,
  "mm_per_arc_segment": 0.1,
  "move_checkers": [
    {
      "axis_limiter": {
        "axis": [
          0.0,
          0.0,
          1.0
        ],
        "max_velocity": 5.0,
        "max_accel": 200.0
      }
    },
    {
      "extruder_limiter": {
        "max_velocity": 79.82432411074329,
        "max_accel": 1596.486482214866
      }
    }
  ]
}

**Comment by sb53systems** [comment]
@dalegaard any future support for this issue ?  
Your help would be very valuable !  
  
Best regards,
Salim

**Comment by dalegaard** [comment]
Hi @sb53systems 

`set_velocity_limit` is supported, so I'm not sure what's wrong here. I don't use `klipper_estimator` anymore and I don't have time to debug the issue. Sorry.

Best regards,
Lasse

**Comment by sb53systems** [comment]
@dalegaard , I confirm that the time estimated by the current version of Klipper Estimator is really accurate (+/- 1S)  
the only difference between the estimated time and the one that the Klipper Firmware calculates, is the purge line (included in the START_PRINT marco) which takes 10s in my case  
![image](https://github.com/user-attachments/assets/f1daed9d-5572-4ff5-b19c-27f61a5d2a3c)  
  
Thank you very much for implementing this tool, it helped me a lot in my last project.  
  
# G-Code Flow and Temperature Controller (using Klipper_Estimator V 3.7.3)
https://github.com/sb53systems/G-Code-Flow-Temperature-Controller  
  
Best Regards.  
Salim
