### ISSUE TITLE
square_corner_velocity does not appear to be factored into calculations

### ISSUE THREAD

**Issue by jrobbom5** [Annex-Engineering/klipper_estimator#67]
Just a very small and relatively inconsequential bug: I noticed that klipper-estimator is not taking the value of square_corner_velocity into account when making calculations. I recently dropped my SQV from the default of 5mm/s down to 2. This leads to a significant increase in printing time of around 30%, however klipper-estimator does not alter its estimate when the value is changed

**Comment by dalegaard** [comment]
Hi,

At the very least I'll need some gcode and json config to reproduce this. SCV is fully modeled.

Best regards, 
Lasse
