### ISSUE TITLE
Klipper_Estimator for RRF gcode files?

### ISSUE THREAD

**Issue by Rickthebig** [Annex-Engineering/klipper_estimator#68]
I intend to use a postprocessor in Orca which depends on Klipper_Estimator. Unfortunately, my printer is RRF based so the Klipper_Estimator does not process my gcode files.

I assume that basic calculations are the same since they are based on the gcode commands themselves. Is there a workaround for this?

**Comment by dalegaard** [comment]
Hi @Rickthebig 

The kinematics used in RRF are different to the ones in Klipper, so the estimates will not be the same. As I don't use RRF(or Klipper anymore) this is not something I intend to add support for in `klipper_estimator`.

Best regards,
Lasse
