### ISSUE TITLE
Fails because klipper deprecated `max_accel_to_decel`

### ISSUE THREAD

**Issue by NameOfTheDragon** [Annex-Engineering/klipper_estimator#70]
Post-processing fails with the following error:

> Failed to load printer configuration: request failed: error decoding response body: missing field `max_accel_to_decel` at line 1 column 33497

Klipper has deprecated this keyword and so it is probable that users have started using the replacement 
 `minimum_cruise_ratio` instead.

**Comment by dalegaard** [comment]
Hi @NameOfTheDragon 

Are you running the latest version?

Best regards,
Lasse

**Comment by NameOfTheDragon** [comment]
> Hi @NameOfTheDragon
> 
> Are you running the latest version?
> 
> Best regards, Lasse

Apparently not! Apologies for the false alarm. I had definitely just re-downloaded it but I think some "helpful" anti-malware might have prevented me from saving it.
