### ISSUE TITLE
Wrong version when compiling

### ISSUE THREAD

**Issue by LeandroMarceddu** [Annex-Engineering/klipper_estimator#8]
You know me, I like to dick around with new stuff. So I was compiling this myself and I noticed the versions in the output never get updated. 

Example: 
![image](https://user-images.githubusercontent.com/227830/151043283-accca8f0-bd09-4fd8-8971-c568f1ee5058.png)

This still displays lib_klipper and klipper_estimator at v0.1.0, while you're still at v1.4.0

**Comment by dalegaard** [comment]
Hi!

Yes, this is intentional :) The version number shown in the compiler output comes from the respective `Cargo.toml` files, but the release version comes from the latest git tag and is set by `vcgen` during build.

I'm too lazy to update the versions in `Cargo.toml` :)

Best regards,
Lasse
